const countries = [
  {
    code: "AF",
    name: "Afghanistan",
    continent: "Asia",
    weatherPattern: "Arid to semi-arid; continental",
    temperatureRange: "-10°C to 40°C",
    notes:
      "Cold winters in mountainous areas; hot, dry summers; limited rainfall",
  },
  {
    code: "AX",
    name: "Åland Islands",
    continent: "Europe",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "-10°C to 20°C",
    notes: "Cold, snowy winters; mild summers; frequent precipitation",
  },
  {
    code: "AL",
    name: "Albania",
    continent: "Europe",
    weatherPattern: "Mediterranean; continental in highlands",
    temperatureRange: "0°C to 30°C",
    notes: "Mild, wet winters; hot, dry summers; snow in mountains",
  },
  {
    code: "DZ",
    name: "Algeria",
    continent: "Africa",
    weatherPattern: "Arid desert; Mediterranean on coast",
    temperatureRange: "5°C to 45°C",
    notes: "Hot, dry summers; mild, wet winters on coast; sandstorms in Sahara",
  },
  {
    code: "AS",
    name: "American Samoa",
    continent: "Oceania",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "High humidity; heavy rainfall; tropical cyclones in wet season",
  },
  {
    code: "AD",
    name: "Andorra",
    continent: "Europe",
    weatherPattern: "Temperate alpine",
    temperatureRange: "-5°C to 25°C",
    notes:
      "Cold, snowy winters; warm, dry summers; high altitude affects climate",
  },
  {
    code: "AO",
    name: "Angola",
    continent: "Africa",
    weatherPattern: "Tropical savanna; arid in south",
    temperatureRange: "15°C to 35°C",
    notes: "Wet season October to May; dry season in southern deserts",
  },
  {
    code: "AI",
    name: "Anguilla",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm year-round; hurricane risk in late summer; low rainfall",
  },
  {
    code: "AQ",
    name: "Antarctica",
    continent: "Antarctica",
    weatherPattern: "Polar desert",
    temperatureRange: "-60°C to 0°C",
    notes: "Extremely cold; minimal precipitation; strong winds",
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; hurricane season June to November",
  },
  {
    code: "AR",
    name: "Argentina",
    continent: "South America",
    weatherPattern: "Temperate to subtropical; arid in Patagonia",
    temperatureRange: "-10°C to 35°C",
    notes: "Warm summers in Buenos Aires; cold, snowy winters in Andes",
  },
  {
    code: "AM",
    name: "Armenia",
    continent: "Asia",
    weatherPattern: "Continental; highland",
    temperatureRange: "-15°C to 30°C",
    notes: "Cold winters with snow; hot, dry summers; cooler in mountains",
  },
  {
    code: "AW",
    name: "Aruba",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "25°C to 32°C",
    notes: "Warm, dry year-round; outside main hurricane belt",
  },
  {
    code: "AU",
    name: "Australia",
    continent: "Oceania",
    weatherPattern: "Mostly arid to semi-arid; tropical in north",
    temperatureRange: "10°C to 40°C",
    notes:
      "Hot summers; bushfire risk in dry areas; wet in northern Queensland",
  },
  {
    code: "AT",
    name: "Austria",
    continent: "Europe",
    weatherPattern: "Temperate continental; alpine",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold, snowy winters in Alps; warm summers; moderate rainfall",
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    continent: "Asia",
    weatherPattern: "Semi-arid to continental",
    temperatureRange: "-10°C to 35°C",
    notes: "Mild winters on coast; hot summers; varied climate by altitude",
  },
  {
    code: "BS",
    name: "Bahamas",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 32°C",
    notes: "Warm, humid; hurricane season June to November",
  },
  {
    code: "BH",
    name: "Bahrain",
    continent: "Asia",
    weatherPattern: "Arid desert",
    temperatureRange: "15°C to 45°C",
    notes: "Hot, humid summers; mild winters; occasional sandstorms",
  },
  {
    code: "BD",
    name: "Bangladesh",
    continent: "Asia",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "15°C to 35°C",
    notes: "Heavy monsoon rains June to September; cyclones in coastal areas",
  },
  {
    code: "BB",
    name: "Barbados",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm year-round; wet season June to November; hurricane risk",
  },
  {
    code: "BY",
    name: "Belarus",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-15°C to 25°C",
    notes: "Cold, snowy winters; mild, wet summers; frequent fog",
  },
  {
    code: "BE",
    name: "Belgium",
    continent: "Europe",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "0°C to 25°C",
    notes: "Mild, wet winters; cool summers; frequent rainfall",
  },
  {
    code: "BZ",
    name: "Belize",
    continent: "North America",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "20°C to 35°C",
    notes: "Hot, humid; wet season June to November; hurricane risk",
  },
  {
    code: "BJ",
    name: "Benin",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season April to October; dry, dusty harmattan in north",
  },
  {
    code: "BM",
    name: "Bermuda",
    continent: "North America",
    weatherPattern: "Subtropical marine",
    temperatureRange: "15°C to 30°C",
    notes: "Mild year-round; hurricane season June to November",
  },
  {
    code: "BT",
    name: "Bhutan",
    continent: "Asia",
    weatherPattern: "Subtropical to alpine",
    temperatureRange: "-10°C to 30°C",
    notes: "Monsoon rains in summer; cold winters in high altitudes",
  },
  {
    code: "BO",
    name: "Bolivia",
    continent: "South America",
    weatherPattern: "Tropical to highland",
    temperatureRange: "0°C to 30°C",
    notes: "Wet season November to March; cooler in Andes highlands",
  },
  {
    code: "BQ",
    name: "Bonaire, Sint Eustatius and Saba",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "25°C to 32°C",
    notes: "Warm, dry; occasional hurricanes; low rainfall",
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold, snowy winters; hot summers; moderate rainfall",
  },
  {
    code: "BW",
    name: "Botswana",
    continent: "Africa",
    weatherPattern: "Semi-arid; subtropical",
    temperatureRange: "5°C to 35°C",
    notes: "Dry winters; hot, wet summers; Kalahari Desert influences",
  },
  {
    code: "BV...",
    name: "Bouvet Island",
    continent: "Antarctica",
    weatherPattern: "Polar tundra",
    temperatureRange: "-15°C to 5°C",
    notes: "Cold, windy; minimal precipitation; mostly ice-covered",
  },
  {
    code: "BR",
    name: "Brazil",
    continent: "South America",
    weatherPattern: "Tropical and subtropical",
    temperatureRange: "20°C to 35°C",
    notes: "Amazon rainforest climate; humid and rainy in north",
  },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    continent: "Asia",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; heavy rainfall; monsoon influence",
  },
  {
    code: "BN",
    name: "Brunei Darussalam",
    continent: "Asia",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "25°C to 35°C",
    notes: "High humidity; heavy rainfall year-round; no distinct dry season",
  },
  {
    code: "BG",
    name: "Bulgaria",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold, snowy winters; hot, dry summers; Black Sea moderates coast",
  },
  {
    code: "BF",
    name: "Burkina Faso",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "20°C to 40°C",
    notes:
      "Dry season November to March; wet season in summer; harmattan winds",
  },
  {
    code: "BI",
    name: "Burundi",
    continent: "Africa",
    weatherPattern: "Tropical highland",
    temperatureRange: "15°C to 30°C",
    notes:
      "Wet seasons March to May and October to December; mild temperatures",
  },
  {
    code: "CV",
    name: "Cabo Verde",
    continent: "Africa",
    weatherPattern: "Arid; tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Dry, warm year-round; occasional tropical storms; harmattan dust",
  },
  {
    code: "KH",
    name: "Cambodia",
    continent: "Asia",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season May to October; dry season; high humidity",
  },
  {
    code: "CM",
    name: "Cameroon",
    continent: "Africa",
    weatherPattern: "Tropical; varied by region",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season in south; drier in north; equatorial in coastal areas",
  },
  {
    code: "CA",
    name: "Canada",
    continent: "North America",
    weatherPattern: "Continental to arctic",
    temperatureRange: "-40°C to 30°C",
    notes: "Harsh winters with heavy snow; mild summers in south",
  },
  {
    code: "KY",
    name: "Cayman Islands",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; hurricane season June to November",
  },
  {
    code: "CF",
    name: "Central African Republic",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season May to October; dry season with harmattan winds",
  },
  {
    code: "TD",
    name: "Chad",
    continent: "Africa",
    weatherPattern: "Arid to tropical savanna",
    temperatureRange: "15°C to 45°C",
    notes: "Hot, dry in north; wet season in south June to September",
  },
  {
    code: "CL",
    name: "Chile",
    continent: "South America",
    weatherPattern: "Varied (arid, temperate, polar)",
    temperatureRange: "-10°C to 35°C",
    notes: "Dry Atacama Desert; Mediterranean in central; cold in Patagonia",
  },
  {
    code: "CN",
    name: "China",
    continent: "Asia",
    weatherPattern: "Varied (continental, subtropical, arid)",
    temperatureRange: "-20°C to 40°C",
    notes: "Monsoons in southeast; cold winters in north; desert in west",
  },
  {
    code: "CX",
    name: "Christmas Island",
    continent: "Asia",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season November to April; cyclone risk",
  },
  {
    code: "CC",
    name: "Cocos (Keeling) Islands",
    continent: "Asia",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season November to April; trade winds",
  },
  {
    code: "CO",
    name: "Colombia",
    continent: "South America",
    weatherPattern: "Tropical; highland in Andes",
    temperatureRange: "10°C to 30°C",
    notes: "Wet and dry seasons; equatorial climate; cooler in highlands",
  },
  {
    code: "KM",
    name: "Comoros",
    continent: "Africa",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season November to April; cyclone risk",
  },
  {
    code: "CG",
    name: "Congo",
    continent: "Africa",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "High humidity; heavy rainfall year-round; short dry season",
  },
  {
    code: "CD",
    name: "Congo, Democratic Republic of the",
    continent: "Africa",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "High humidity; heavy rainfall; equatorial climate",
  },
  {
    code: "CK",
    name: "Cook Islands",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season November to March; cyclone risk",
  },
  {
    code: "CR",
    name: "Costa Rica",
    continent: "North America",
    weatherPattern: "Tropical; highland",
    temperatureRange: "15°C to 30°C",
    notes: "Wet season May to November; dry season; varied by altitude",
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season May to October; dry season with harmattan winds",
  },
  {
    code: "HR",
    name: "Croatia",
    continent: "Europe",
    weatherPattern: "Mediterranean; continental inland",
    temperatureRange: "-5°C to 30°C",
    notes: "Hot, dry summers on coast; cold, snowy winters inland",
  },
  {
    code: "CU",
    name: "Cuba",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season May to October; hurricane risk",
  },
  {
    code: "CW",
    name: "Curaçao",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "25°C to 32°C",
    notes: "Warm, dry; outside main hurricane belt; low rainfall",
  },
  {
    code: "CY",
    name: "Cyprus",
    continent: "Asia",
    weatherPattern: "Mediterranean",
    temperatureRange: "5°C to 35°C",
    notes: "Hot, dry summers; mild, wet winters; occasional dust storms",
  },
  {
    code: "CZ",
    name: "Czechia",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold, snowy winters; warm summers; moderate rainfall",
  },
  {
    code: "DK",
    name: "Denmark",
    continent: "Europe",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "-5°C to 25°C",
    notes: "Mild, wet winters; cool summers; frequent storms",
  },
  {
    code: "DJ",
    name: "Djibouti",
    continent: "Africa",
    weatherPattern: "Arid desert",
    temperatureRange: "20°C to 45°C",
    notes: "Hot, dry year-round; minimal rainfall; high humidity on coast",
  },
  {
    code: "DM",
    name: "Dominica",
    continent: "North America",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; heavy rainfall; hurricane season June to November",
  },
  {
    code: "DO",
    name: "Dominican Republic",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 32°C",
    notes: "Warm, humid; wet season May to November; hurricane risk",
  },
  {
    code: "EC",
    name: "Ecuador",
    continent: "South America",
    weatherPattern: "Tropical; highland",
    temperatureRange: "10°C to 30°C",
    notes: "Equatorial climate; wet and dry seasons; cooler in Andes",
  },
  {
    code: "EG",
    name: "Egypt",
    continent: "Africa",
    weatherPattern: "Arid desert",
    temperatureRange: "10°C to 45°C",
    notes: "Hot, dry summers; mild winters; minimal rainfall except on coast",
  },
  {
    code: "SV",
    name: "El Salvador",
    continent: "North America",
    weatherPattern: "Tropical savanna",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season May to October; dry season; hurricane risk",
  },
  {
    code: "GQ",
    name: "Equatorial Guinea",
    continent: "Africa",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "High humidity; heavy rainfall year-round; short dry season",
  },
  {
    code: "ER",
    name: "Eritrea",
    continent: "Africa",
    weatherPattern: "Arid to tropical",
    temperatureRange: "15°C to 40°C",
    notes:
      "Hot, dry coastal plains; cooler, wetter highlands; minimal rainfall",
  },
  {
    code: "EE",
    name: "Estonia",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-15°C to 25°C",
    notes: "Cold, snowy winters; mild summers; Baltic Sea influence",
  },
  {
    code: "SZ",
    name: "Eswatini",
    continent: "Africa",
    weatherPattern: "Subtropical",
    temperatureRange: "10°C to 30°C",
    notes: "Wet summers; dry winters; cooler in highlands",
  },
  {
    code: "ET",
    name: "Ethiopia",
    continent: "Africa",
    weatherPattern: "Tropical highland",
    temperatureRange: "5°C to 30°C",
    notes: "Wet season June to September; dry season; cooler in highlands",
  },
  {
    code: "FK",
    name: "Falkland Islands (Malvinas)",
    continent: "South America",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "-5°C to 15°C",
    notes: "Cool, wet, windy year-round; occasional snow in winter",
  },
  {
    code: "FO",
    name: "Faroe Islands",
    continent: "Europe",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "0°C to 15°C",
    notes: "Mild, wet winters; cool summers; frequent storms",
  },
  {
    code: "FJ",
    name: "Fiji",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season November to April; cyclone risk",
  },
  {
    code: "FI",
    name: "Finland",
    continent: "Europe",
    weatherPattern: "Subarctic to temperate",
    temperatureRange: "-30°C to 25°C",
    notes: "Long, cold winters; short, mild summers; heavy snow in north",
  },
  {
    code: "FR",
    name: "France",
    continent: "Europe",
    weatherPattern: "Temperate; Mediterranean in south",
    temperatureRange: "0°C to 35°C",
    notes: "Mild, wet winters; warm summers; hot in Riviera",
  },
  {
    code: "GF",
    name: "French Guiana",
    continent: "South America",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "Hot, humid; heavy rainfall year-round; short dry season",
  },
  {
    code: "PF",
    name: "French Polynesia",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season November to April; cyclone risk",
  },
  {
    code: "TF",
    name: "French Southern Territories",
    continent: "Antarctica",
    weatherPattern: "Polar to subpolar",
    temperatureRange: "-10°C to 10°C",
    notes: "Cold, windy; minimal precipitation; mostly uninhabited",
  },
  {
    code: "GA",
    name: "Gabon",
    continent: "Africa",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "Hot, humid; heavy rainfall; short dry season July to August",
  },
  {
    code: "GM",
    name: "Gambia",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season June to October; dry season with harmattan winds",
  },
  {
    code: "GE",
    name: "Georgia",
    continent: "Asia",
    weatherPattern: "Temperate to subtropical",
    temperatureRange: "-5°C to 30°C",
    notes: "Mild winters on coast; cold, snowy winters in mountains",
  },
  {
    code: "DE",
    name: "Germany",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold, wet winters; warm summers; occasional heatwaves",
  },
  {
    code: "GH",
    name: "Ghana",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season April to October; dry season with harmattan winds",
  },
  {
    code: "GI",
    name: "Gibraltar",
    continent: "Europe",
    weatherPattern: "Mediterranean",
    temperatureRange: "10°C to 30°C",
    notes: "Mild, wet winters; hot, dry summers; occasional storms",
  },
  {
    code: "GR",
    name: "Greece",
    continent: "Europe",
    weatherPattern: "Mediterranean",
    temperatureRange: "0°C to 35°C",
    notes: "Hot, dry summers; mild, wet winters; cooler in mountains",
  },
  {
    code: "GL",
    name: "Greenland",
    continent: "North America",
    weatherPattern: "Polar tundra to arctic",
    temperatureRange: "-40°C to 10°C",
    notes: "Extremely cold; heavy snow; short, cool summers",
  },
  {
    code: "GD",
    name: "Grenada",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "GP",
    name: "Guadeloupe",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "GU",
    name: "Guam",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season July to November; typhoon risk",
  },
  {
    code: "GT",
    name: "Guatemala",
    continent: "North America",
    weatherPattern: "Tropical; highland",
    temperatureRange: "15°C to 30°C",
    notes: "Wet season May to October; dry season; cooler in highlands",
  },
  {
    code: "GG",
    name: "Guernsey",
    continent: "Europe",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "5°C to 20°C",
    notes: "Mild, wet winters; cool summers; frequent fog",
  },
  {
    code: "GN",
    name: "Guinea",
    continent: "Africa",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season May to October; dry season with harmattan winds",
  },
  {
    code: "GW",
    name: "Guinea-Bissau",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season June to November; dry season; high humidity",
  },
  {
    code: "GY",
    name: "Guyana",
    continent: "South America",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "Hot, humid; two wet seasons (May-June, November-January)",
  },
  {
    code: "HT",
    name: "Haiti",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 35°C",
    notes: "Warm, humid; wet season April to November; hurricane risk",
  },
  {
    code: "HM",
    name: "Heard Island and McDonald Islands",
    continent: "Antarctica",
    weatherPattern: "Polar tundra",
    temperatureRange: "-10°C to 5°C",
    notes: "Cold, windy; minimal precipitation; mostly uninhabited",
  },
  {
    code: "VA",
    name: "Holy See",
    continent: "Europe",
    weatherPattern: "Mediterranean",
    temperatureRange: "0°C to 30°C",
    notes: "Mild, wet winters; hot, dry summers; urban microclimate",
  },
  {
    code: "HN",
    name: "Honduras",
    continent: "North America",
    weatherPattern: "Tropical; highland",
    temperatureRange: "15°C to 35°C",
    notes: "Wet season May to November; dry season; hurricane risk",
  },
  {
    code: "HK",
    name: "Hong Kong",
    continent: "Asia",
    weatherPattern: "Subtropical monsoon",
    temperatureRange: "10°C to 35°C",
    notes: "Hot, humid summers; mild winters; typhoons in summer",
  },
  {
    code: "HU",
    name: "Hungary",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold winters; hot summers; moderate rainfall",
  },
  {
    code: "IS",
    name: "Iceland",
    continent: "Europe",
    weatherPattern: "Subpolar oceanic",
    temperatureRange: "-10°C to 15°C",
    notes: "Mild winters; cool summers; frequent rain and wind",
  },
  {
    code: "IN",
    name: "India",
    continent: "Asia",
    weatherPattern: "Tropical and subtropical",
    temperatureRange: "5°C to 45°C",
    notes:
      "Monsoon rains from June to September; hot summers and cool winters in north",
  },
  {
    code: "ID",
    name: "Indonesia",
    continent: "Asia",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 35°C",
    notes: "High humidity; heavy rainfall year-round; dry season in some areas",
  },
  {
    code: "IR",
    name: "Iran",
    continent: "Asia",
    weatherPattern: "Arid to semi-arid; continental",
    temperatureRange: "-10°C to 45°C",
    notes: "Hot summers; cold winters in highlands; minimal rainfall",
  },
  {
    code: "IQ",
    name: "Iraq",
    continent: "Asia",
    weatherPattern: "Arid desert; continental",
    temperatureRange: "0°C to 50°C",
    notes: "Extremely hot summers; cold winters; dust storms common",
  },
  {
    code: "IE",
    name: "Ireland",
    continent: "Europe",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "0°C to 20°C",
    notes: "Mild, wet winters; cool summers; frequent rainfall",
  },
  {
    code: "IM",
    name: "Isle of Man",
    continent: "Europe",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "0°C to 20°C",
    notes: "Mild, wet winters; cool summers; frequent fog",
  },
  {
    code: "IL",
    name: "Israel",
    continent: "Asia",
    weatherPattern: "Mediterranean; arid in south",
    temperatureRange: "5°C to 40°C",
    notes: "Hot, dry summers; mild, wet winters; desert conditions in Negev",
  },
  {
    code: "IT",
    name: "Italy",
    continent: "Europe",
    weatherPattern: "Mediterranean; alpine in north",
    temperatureRange: "-10°C to 35°C",
    notes: "Hot summers; mild winters in south; snowy in Alps",
  },
  {
    code: "JM",
    name: "Jamaica",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season May to November; hurricane risk",
  },
  {
    code: "JP",
    name: "Japan",
    continent: "Asia",
    weatherPattern: "Temperate to subtropical",
    temperatureRange: "-10°C to 35°C",
    notes:
      "Rainy season in June; typhoons in late summer; snowy winters in north",
  },
  {
    code: "JE",
    name: "Jersey",
    continent: "Europe",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "5°C to 20°C",
    notes: "Mild, wet winters; cool summers; occasional storms",
  },
  {
    code: "JO",
    name: "Jordan",
    continent: "Asia",
    weatherPattern: "Arid desert; Mediterranean on highlands",
    temperatureRange: "0°C to 40°C",
    notes: "Hot, dry summers; cool, wet winters; desert conditions dominate",
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    continent: "Asia",
    weatherPattern: "Continental; arid",
    temperatureRange: "-30°C to 35°C",
    notes: "Harsh winters; hot summers; low precipitation in steppes",
  },
  {
    code: "KE",
    name: "Kenya",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "10°C to 30°C",
    notes: "Dry and wet seasons; cooler in highlands; warm along coast",
  },
  {
    code: "KI",
    name: "Kiribati",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "25°C to 30°C",
    notes: "Warm, humid; wet year-round; occasional cyclones",
  },
  {
    code: "KP",
    name: "Korea, Democratic People's Republic of",
    continent: "Asia",
    weatherPattern: "Temperate continental",
    temperatureRange: "-20°C to 30°C",
    notes: "Cold winters; hot, humid summers; monsoon rains in summer",
  },
  {
    code: "KR",
    name: "Korea, Republic of",
    continent: "Asia",
    weatherPattern: "Temperate continental",
    temperatureRange: "-15°C to 35°C",
    notes: "Cold winters; hot, humid summers; monsoon rains in summer",
  },
  {
    code: "KW",
    name: "Kuwait",
    continent: "Asia",
    weatherPattern: "Arid desert",
    temperatureRange: "10°C to 50°C",
    notes: "Extremely hot summers; mild winters; frequent sandstorms",
  },
  {
    code: "KG",
    name: "Kyrgyzstan",
    continent: "Asia",
    weatherPattern: "Continental; highland",
    temperatureRange: "-20°C to 30°C",
    notes: "Cold winters with snow; hot summers; cooler in mountains",
  },
  {
    code: "LA",
    name: "Lao People's Democratic Republic",
    continent: "Asia",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "15°C to 35°C",
    notes: "Wet season May to October; dry season; high humidity",
  },
  {
    code: "LV",
    name: "Latvia",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-15°C to 25°C",
    notes: "Cold, snowy winters; mild summers; Baltic Sea influence",
  },
  {
    code: "LB",
    name: "Lebanon",
    continent: "Asia",
    weatherPattern: "Mediterranean",
    temperatureRange: "5°C to 35°C",
    notes: "Mild, wet winters; hot, dry summers; snow in mountains",
  },
  {
    code: "LS",
    name: "Lesotho",
    continent: "Africa",
    weatherPattern: "Temperate highland",
    temperatureRange: "-5°C to 30°C",
    notes: "Dry winters; wet summers; snow in highlands",
  },
  {
    code: "LR",
    name: "Liberia",
    continent: "Africa",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "20°C to 35°C",
    notes: "Heavy rainfall year-round; wet season May to October",
  },
  {
    code: "LY",
    name: "Libya",
    continent: "Africa",
    weatherPattern: "Arid desert",
    temperatureRange: "10°C to 45°C",
    notes: "Hot, dry summers; mild winters; sandstorms in Sahara",
  },
  {
    code: "LI",
    name: "Liechtenstein",
    continent: "Europe",
    weatherPattern: "Temperate alpine",
    temperatureRange: "-10°C to 25°C",
    notes: "Cold, snowy winters; warm summers; moderate rainfall",
  },
  {
    code: "LT",
    name: "Lithuania",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-15°C to 25°C",
    notes: "Cold, snowy winters; mild summers; Baltic Sea influence",
  },
  {
    code: "LU",
    name: "Luxembourg",
    continent: "Europe",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "-5°C to 25°C",
    notes: "Mild, wet winters; cool summers; moderate rainfall",
  },
  {
    code: "MO",
    name: "Macao",
    continent: "Asia",
    weatherPattern: "Subtropical monsoon",
    temperatureRange: "10°C to 35°C",
    notes: "Hot, humid summers; mild winters; typhoons in summer",
  },
  {
    code: "MG",
    name: "Madagascar",
    continent: "Africa",
    weatherPattern: "Tropical; subtropical in highlands",
    temperatureRange: "10°C to 30°C",
    notes: "Wet season November to April; cyclones in east; dry in west",
  },
  {
    code: "MW",
    name: "Malawi",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "15°C to 30°C",
    notes: "Wet season November to April; dry season; cooler in highlands",
  },
  {
    code: "MY",
    name: "Malaysia",
    continent: "Asia",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 35°C",
    notes: "High humidity; heavy rainfall year-round; monsoon seasons",
  },
  {
    code: "MV",
    name: "Maldives",
    continent: "Asia",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "25°C to 30°C",
    notes: "Warm, humid; wet season May to October; cyclone risk",
  },
  {
    code: "ML",
    name: "Mali",
    continent: "Africa",
    weatherPattern: "Arid to tropical savanna",
    temperatureRange: "15°C to 45°C",
    notes: "Hot, dry in north; wet season in south June to September",
  },
  {
    code: "MT",
    name: "Malta",
    continent: "Europe",
    weatherPattern: "Mediterranean",
    temperatureRange: "10°C to 30°C",
    notes: "Hot, dry summers; mild, wet winters; occasional storms",
  },
  {
    code: "MH",
    name: "Marshall Islands",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "25°C to 30°C",
    notes: "Warm, humid; wet year-round; occasional typhoons",
  },
  {
    code: "MQ",
    name: "Martinique",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "MR",
    name: "Mauritania",
    continent: "Africa",
    weatherPattern: "Arid desert",
    temperatureRange: "15°C to 45°C",
    notes: "Hot, dry; minimal rainfall; harmattan winds in dry season",
  },
  {
    code: "MU",
    name: "Mauritius",
    continent: "Africa",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season January to March; cyclone risk",
  },
  {
    code: "YT",
    name: "Mayotte",
    continent: "Africa",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season November to April; cyclone risk",
  },
  {
    code: "MX",
    name: "Mexico",
    continent: "North America",
    weatherPattern: "Varied (tropical, arid, temperate)",
    temperatureRange: "5°C to 40°C",
    notes: "Dry winters; wet summers; hurricanes on coasts",
  },
  {
    code: "FM",
    name: "Micronesia, Federated States of",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "25°C to 30°C",
    notes: "Warm, humid; wet year-round; typhoon risk",
  },
  {
    code: "MD",
    name: "Moldova, Republic of",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold winters; hot summers; moderate rainfall",
  },
  {
    code: "MC",
    name: "Monaco",
    continent: "Europe",
    weatherPattern: "Mediterranean",
    temperatureRange: "5°C to 30°C",
    notes: "Mild, wet winters; hot, dry summers; urban microclimate",
  },
  {
    code: "MN",
    name: "Mongolia",
    continent: "Asia",
    weatherPattern: "Continental; arid",
    temperatureRange: "-40°C to 30°C",
    notes: "Harsh, cold winters; hot summers; low precipitation",
  },
  {
    code: "ME",
    name: "Montenegro",
    continent: "Europe",
    weatherPattern: "Mediterranean; continental inland",
    temperatureRange: "-5°C to 30°C",
    notes: "Hot summers on coast; cold, snowy winters inland",
  },
  {
    code: "MS",
    name: "Montserrat",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "MA",
    name: "Morocco",
    continent: "Africa",
    weatherPattern: "Mediterranean; arid inland",
    temperatureRange: "5°C to 40°C",
    notes: "Hot summers; mild winters on coast; cold in Atlas Mountains",
  },
  {
    code: "MZ",
    name: "Mozambique",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "15°C to 30°C",
    notes: "Wet season October to March; dry season; cyclones in south",
  },
  {
    code: "MM",
    name: "Myanmar",
    continent: "Asia",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "15°C to 35°C",
    notes: "Wet season May to October; dry season; cyclones in coastal areas",
  },
  {
    code: "NA",
    name: "Namibia",
    continent: "Africa",
    weatherPattern: "Arid to semi-arid",
    temperatureRange: "5°C to 35°C",
    notes: "Hot, dry; minimal rainfall; cooler along coast",
  },
  {
    code: "NR",
    name: "Nauru",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "25°C to 30°C",
    notes: "Warm, humid; wet year-round; occasional droughts",
  },
  {
    code: "NP",
    name: "Nepal",
    continent: "Asia",
    weatherPattern: "Subtropical to alpine",
    temperatureRange: "-10°C to 30°C",
    notes: "Monsoon rains June to September; cold winters in Himalayas",
  },
  {
    code: "NL",
    name: "Netherlands",
    continent: "Europe",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "0°C to 25°C",
    notes: "Mild, wet winters; cool summers; frequent rainfall",
  },
  {
    code: "NC",
    name: "New Caledonia",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season January to March; cyclone risk",
  },
  {
    code: "NZ",
    name: "New Zealand",
    continent: "Oceania",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "0°C to 25°C",
    notes: "Mild, wet winters; warm summers; variable by region",
  },
  {
    code: "NI",
    name: "Nicaragua",
    continent: "North America",
    weatherPattern: "Tropical; highland",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season May to November; dry season; hurricane risk",
  },
  {
    code: "NE",
    name: "Niger",
    continent: "Africa",
    weatherPattern: "Arid desert",
    temperatureRange: "15°C to 45°C",
    notes: "Hot, dry; minimal rainfall; harmattan winds in dry season",
  },
  {
    code: "NG",
    name: "Nigeria",
    continent: "Africa",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season April to October; dry, dusty harmattan in north",
  },
  {
    code: "NU",
    name: "Niue",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season November to April; cyclone risk",
  },
  {
    code: "NF",
    name: "Norfolk Island",
    continent: "Oceania",
    weatherPattern: "Subtropical marine",
    temperatureRange: "15°C to 25°C",
    notes: "Mild year-round; wetter in winter; occasional storms",
  },
  {
    code: "MK",
    name: "North Macedonia",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold winters; hot, dry summers; moderate rainfall",
  },
  {
    code: "MP",
    name: "Northern Mariana Islands",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season July to November; typhoon risk",
  },
  {
    code: "NO",
    name: "Norway",
    continent: "Europe",
    weatherPattern: "Temperate to subarctic",
    temperatureRange: "-20°C to 25°C",
    notes: "Cold, snowy winters; mild summers; wet along coast",
  },
  {
    code: "OM",
    name: "Oman",
    continent: "Asia",
    weatherPattern: "Arid desert",
    temperatureRange: "15°C to 45°C",
    notes: "Hot, dry summers; mild winters; occasional cyclones",
  },
  {
    code: "PK",
    name: "Pakistan",
    continent: "Asia",
    weatherPattern: "Arid to subtropical",
    temperatureRange: "0°C to 45°C",
    notes: "Monsoon rains July to September; hot summers; cold in north",
  },
  {
    code: "PW",
    name: "Palau",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "25°C to 30°C",
    notes: "Warm, humid; wet year-round; typhoon risk",
  },
  {
    code: "PS",
    name: "Palestine, State of",
    continent: "Asia",
    weatherPattern: "Mediterranean; arid in south",
    temperatureRange: "5°C to 35°C",
    notes: "Hot, dry summers; mild, wet winters; desert in south",
  },
  {
    code: "PA",
    name: "Panama",
    continent: "North America",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "Hot, humid; wet season May to December; dry season",
  },
  {
    code: "PNG",
    name: "Papua New Guinea",
    continent: "Oceania",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "High humidity; heavy rainfall year-round; wetter in highlands",
  },
  {
    code: "PY",
    name: "Paraguay",
    continent: "South America",
    weatherPattern: "Subtropical",
    temperatureRange: "10°C to 35°C",
    notes: "Wet summers; dry winters; hot in Chaco region",
  },
  {
    code: "PE",
    name: "Peru",
    continent: "South America",
    weatherPattern: "Tropical; highland; arid",
    temperatureRange: "0°C to 30°C",
    notes: "Wet season in Andes; dry coastal desert; equatorial in Amazon",
  },
  {
    code: "PH",
    name: "Philippines",
    continent: "Asia",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season June to November; typhoons; dry season",
  },
  {
    code: "PN",
    name: "Pitcairn",
    continent: "Oceania",
    weatherPattern: "Subtropical marine",
    temperatureRange: "15°C to 25°C",
    notes: "Mild, humid; wetter in winter; occasional storms",
  },
  {
    code: "PL",
    name: "Poland",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold, snowy winters; warm summers; moderate rainfall",
  },
  {
    code: "PT",
    name: "Portugal",
    continent: "Europe",
    weatherPattern: "Mediterranean; temperate oceanic",
    temperatureRange: "5°C to 35°C",
    notes: "Hot, dry summers; mild, wet winters; cooler in north",
  },
  {
    code: "PR",
    name: "Puerto Rico",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season May to October; hurricane risk",
  },
  {
    code: "QA",
    name: "Qatar",
    continent: "Asia",
    weatherPattern: "Arid desert",
    temperatureRange: "15°C to 45°C",
    notes: "Hot, humid summers; mild winters; occasional sandstorms",
  },
  {
    code: "RE",
    name: "Réunion",
    continent: "Africa",
    weatherPattern: "T зареropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season January to March; cyclone risk",
  },
  {
    code: "RO",
    name: "Romania",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold, snowy winters; hot summers; Black Sea moderates coast",
  },
  {
    code: "RU",
    name: "Russian Federation",
    continent: "Europe/Asia",
    weatherPattern: "Continental and subarctic",
    temperatureRange: "-50°C to 30°C",
    notes: "Long, harsh winters in Siberia; moderate summer temperatures",
  },
  {
    code: "RW",
    name: "Rwanda",
    continent: "Africa",
    weatherPattern: "Tropical highland",
    temperatureRange: "15°C to 30°C",
    notes:
      "Wet seasons March to May and October to December; mild temperatures",
  },
  {
    code: "BL",
    name: "Saint Barthélemy",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "SH",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    continent: "Africa",
    weatherPattern: "Subtropical to temperate",
    temperatureRange: "15°C to 25°C",
    notes: "Mild, wet; varies by island; cooler in higher elevations",
  },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "LC",
    name: "Saint Lucia",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "MF",
    name: "Saint Martin (French part)",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "PM",
    name: "Saint Pierre and Miquelon",
    continent: "North America",
    weatherPattern: "Subpolar oceanic",
    temperatureRange: "-10°C to 15°C",
    notes: "Cold, wet winters; cool summers; frequent fog",
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "WS",
    name: "Samoa",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season November to April; cyclone risk",
  },
  {
    code: "SM",
    name: "San Marino",
    continent: "Europe",
    weatherPattern: "Mediterranean",
    temperatureRange: "0°C to 30°C",
    notes: "Mild, wet winters; hot, dry summers; cooler in hills",
  },
  {
    code: "ST",
    name: "Sao Tome and Principe",
    continent: "Africa",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "Hot, humid; heavy rainfall; short dry season June to August",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    continent: "Asia",
    weatherPattern: "Arid desert",
    temperatureRange: "10°C to 50°C",
    notes: "Extremely hot summers; mild winters; very low rainfall",
  },
  {
    code: "SN",
    name: "Senegal",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season June to October; dry season with harmattan winds",
  },
  {
    code: "RS",
    name: "Serbia",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold winters; hot summers; moderate rainfall",
  },
  {
    code: "SC",
    name: "Seychelles",
    continent: "Africa",
    weatherPattern: "Tropical marine",
    temperatureRange: "25°C to 30°C",
    notes: "Warm, humid; wet season December to March; trade winds",
  },
  {
    code: "SL",
    name: "Sierra Leone",
    continent: "Africa",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season May to October; dry season with harmattan winds",
  },
  {
    code: "SG",
    name: "Singapore",
    continent: "Asia",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "25°C to 35°C",
    notes: "High humidity; heavy rainfall year-round; no distinct dry season",
  },
  {
    code: "SX",
    name: "Sint Maarten (Dutch part)",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "SK",
    name: "Slovakia",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold, snowy winters; warm summers; moderate rainfall",
  },
  {
    code: "SI",
    name: "Slovenia",
    continent: "Europe",
    weatherPattern: "Temperate continental; Mediterranean on coast",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold winters; hot summers; mild, wet coast",
  },
  {
    code: "SB",
    name: "Solomon Islands",
    continent: "Oceania",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; heavy rainfall year-round; cyclone risk",
  },
  {
    code: "SO",
    name: "Somalia",
    continent: "Africa",
    weatherPattern: "Arid to semi-arid",
    temperatureRange: "20°C to 40°C",
    notes: "Hot, dry; two wet seasons (April-June, October-November)",
  },
  {
    code: "ZA",
    name: "South Africa",
    continent: "Africa",
    weatherPattern: "Temperate; subtropical in east",
    temperatureRange: "0°C to 35°C",
    notes: "Dry winters; wet summers in east; arid in west",
  },
  {
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
    continent: "Antarctica",
    weatherPattern: "Polar tundra",
    temperatureRange: "-15°C to 5°C",
    notes: "Cold, windy; minimal precipitation; mostly ice-covered",
  },
  {
    code: "SS",
    name: "South Sudan",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "20°C to 40°C",
    notes: "Wet season April to October; dry season; high humidity",
  },
  {
    code: "ES",
    name: "Spain",
    continent: "Europe",
    weatherPattern: "Mediterranean; temperate in north",
    temperatureRange: "0°C to 35°C",
    notes: "Hot, dry summers; mild, wet winters; cooler in north",
  },
  {
    code: "LK",
    name: "Sri Lanka",
    continent: "Asia",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "20°C to 35°C",
    notes: "Wet seasons vary by region; high humidity; cyclones",
  },
  {
    code: "SD",
    name: "Sudan",
    continent: "Africa",
    weatherPattern: "Arid to tropical savanna",
    temperatureRange: "15°C to 45°C",
    notes: "Hot, dry in north; wet season in south June to September",
  },
  {
    code: "SR",
    name: "Suriname",
    continent: "South America",
    weatherPattern: "Tropical rainforest",
    temperatureRange: "20°C to 30°C",
    notes: "Hot, humid; two wet seasons (April-August, November-January)",
  },
  {
    code: "SJ",
    name: "Svalbard and Jan Mayen",
    continent: "Europe",
    weatherPattern: "Polar tundra",
    temperatureRange: "-20°C to 5°C",
    notes: "Cold, snowy; short, cool summers; strong winds",
  },
  {
    code: "SE",
    name: "Sweden",
    continent: "Europe",
    weatherPattern: "Temperate to subarctic",
    temperatureRange: "-20°C to 25°C",
    notes: "Cold, snowy winters; mild summers; wetter in south",
  },
  {
    code: "CH",
    name: "Switzerland",
    continent: "Europe",
    weatherPattern: "Temperate alpine",
    temperatureRange: "-10°C to 30°C",
    notes: "Cold, snowy winters; warm summers; varied by altitude",
  },
  {
    code: "SY",
    name: "Syrian Arab Republic",
    continent: "Asia",
    weatherPattern: "Arid; Mediterranean on coast",
    temperatureRange: "0°C to 40°C",
    notes: "Hot, dry summers; mild, wet winters on coast; desert inland",
  },
  {
    code: "TW",
    name: "Taiwan, Province of China",
    continent: "Asia",
    weatherPattern: "Subtropical monsoon",
    temperatureRange: "10°C to 35°C",
    notes: "Hot, humid summers; mild winters; typhoons in summer",
  },
  {
    code: "TJ",
    name: "Tajikistan",
    continent: "Asia",
    weatherPattern: "Continental; highland",
    temperatureRange: "-20°C to 30°C",
    notes: "Cold winters with snow; hot summers; cooler in mountains",
  },
  {
    code: "TZ",
    name: "Tanzania, United Republic of",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "15°C to 30°C",
    notes: "Wet seasons November to May; dry season; cooler in highlands",
  },
  {
    code: "TH",
    name: "Thailand",
    continent: "Asia",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season May to October; dry season; high humidity",
  },
  {
    code: "TL",
    name: "Timor-Leste",
    continent: "Asia",
    weatherPattern: "Tropical savanna",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season November to April; dry season; high humidity",
  },
  {
    code: "TG",
    name: "Togo",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "20°C to 35°C",
    notes: "Wet season April to October; dry season with harmattan winds",
  },
  {
    code: "TK",
    name: "Tokelau",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "25°C to 30°C",
    notes: "Warm, humid; wet year-round; occasional cyclones",
  },
  {
    code: "TO",
    name: "Tonga",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season November to April; cyclone risk",
  },
  {
    code: "TT",
    name: "Trinidad and Tobago",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to December; hurricane risk",
  },
  {
    code: "TN",
    name: "Tunisia",
    continent: "Africa",
    weatherPattern: "Mediterranean; arid inland",
    temperatureRange: "5°C to 40°C",
    notes: "Hot summers; mild winters on coast; desert conditions inland",
  },
  {
    code: "TR",
    name: "Turkey",
    continent: "Asia/Europe",
    weatherPattern: "Mediterranean; continental inland",
    temperatureRange: "-10°C to 35°C",
    notes: "Hot summers; cold winters inland; mild, wet on coasts",
  },
  {
    code: "TM",
    name: "Turkmenistan",
    continent: "Asia",
    weatherPattern: "Arid continental",
    temperatureRange: "-10°C to 40°C",
    notes: "Hot summers; cold winters; low precipitation; dust storms",
  },
  {
    code: "TC",
    name: "Turks and Caicos Islands",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "TV",
    name: "Tuvalu",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "25°C to 30°C",
    notes: "Warm, humid; wet year-round; cyclone risk",
  },
  {
    code: "UG",
    name: "Uganda",
    continent: "Africa",
    weatherPattern: "Tropical highland",
    temperatureRange: "15°C to 30°C",
    notes:
      "Wet seasons March to May and October to December; mild temperatures",
  },
  {
    code: "UA",
    name: "Ukraine",
    continent: "Europe",
    weatherPattern: "Temperate continental",
    temperatureRange: "-15°C to 30°C",
    notes: "Cold, snowy winters; warm summers; Black Sea moderates south",
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    continent: "Asia",
    weatherPattern: "Arid desert",
    temperatureRange: "15°C to 45°C",
    notes: "Hot, humid summers; mild winters; occasional sandstorms",
  },
  {
    code: "GB",
    name: "United Kingdom",
    continent: "Europe",
    weatherPattern: "Temperate oceanic",
    temperatureRange: "0°C to 30°C",
    notes: "Mild, wet winters; cool summers; frequent rain year-round",
  },
  {
    code: "US",
    name: "United States",
    continent: "North America",
    weatherPattern:
      "Varied (arctic in Alaska, tropical in Florida, arid in southwest)",
    temperatureRange: "-30°C to 40°C",
    notes:
      "Severe winters in north; tornado-prone Midwest; hurricanes on East Coast",
  },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet year-round; typhoon risk",
  },
  {
    code: "UY",
    name: "Uruguay",
    continent: "South America",
    weatherPattern: "Temperate",
    temperatureRange: "5°C to 30°C",
    notes: "Mild winters; warm summers; even rainfall year-round",
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    continent: "Asia",
    weatherPattern: "Arid continental",
    temperatureRange: "-15°C to 40°C",
    notes: "Hot summers; cold winters; low precipitation; dust storms",
  },
  {
    code: "VU",
    name: "Vanuatu",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season November to April; cyclone risk",
  },
  {
    code: "VE",
    name: "Venezuela",
    continent: "South America",
    weatherPattern: "Tropical; highland",
    temperatureRange: "15°C to 35°C",
    notes: "Wet season May to November; dry season; cooler in Andes",
  },
  {
    code: "VN",
    name: "Viet Nam",
    continent: "Asia",
    weatherPattern: "Tropical monsoon",
    temperatureRange: "15°C to 35°C",
    notes: "Wet season May to October; dry season; typhoons in north",
  },
  {
    code: "VG",
    name: "Virgin Islands (British)",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "VI",
    name: "Virgin Islands (U.S.)",
    continent: "North America",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season June to November; hurricane risk",
  },
  {
    code: "WF",
    name: "Wallis and Futuna",
    continent: "Oceania",
    weatherPattern: "Tropical marine",
    temperatureRange: "20°C to 30°C",
    notes: "Warm, humid; wet season November to April; cyclone risk",
  },
  {
    code: "EH",
    name: "Western Sahara",
    continent: "Africa",
    weatherPattern: "Arid desert",
    temperatureRange: "10°C to 40°C",
    notes: "Hot, dry; minimal rainfall; coastal fog moderates temperatures",
  },
  {
    code: "YE",
    name: "Yemen",
    continent: "Asia",
    weatherPattern: "Arid desert",
    temperatureRange: "10°C to 40°C",
    notes: "Hot, dry; monsoon rains in south; minimal rainfall inland",
  },
  {
    code: "ZM",
    name: "Zambia",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "15°C to 35°C",
    notes: "Wet season November to April; dry season; cooler in highlands",
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    continent: "Africa",
    weatherPattern: "Tropical savanna",
    temperatureRange: "10°C to 35°C",
    notes: "Wet season November to March; dry season; cooler in highlands",
  },
];
const topCitiesInIndia = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
];
